<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.2 on win32)" generated="20200330 14:36:12.900" rpa="false">
<suite id="s1" name="TestAPI" source="G:\RobotFrameWork\RobotFrameworkBasic\SuiteSiteTestePratico\AutomacaoDeTesteComRobotFramework_Basico\test\TestAPI.robot">
<kw name="Conectar a minha API" type="setup">
<msg timestamp="20200330 14:36:12.978" level="FAIL">No keyword with name 'Conectar a minha API' found.</msg>
<status status="FAIL" starttime="20200330 14:36:12.978" endtime="20200330 14:36:12.978"></status>
</kw>
<test id="s1-t1" name="Requisitar a listagem de todos os livres(GET em todos os Livros)">
<status status="FAIL" starttime="20200330 14:36:12.978" endtime="20200330 14:36:12.979" critical="yes">Parent suite setup failed:
No keyword with name 'Conectar a minha API' found.</status>
</test>
<doc>Documentação da API:</doc>
<status status="FAIL" starttime="20200330 14:36:12.903" endtime="20200330 14:36:12.981">Suite setup failed:
No keyword with name 'Conectar a minha API' found.</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TestAPI">TestAPI</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200330 14:36:12.948" level="ERROR">Error in file 'G:\RobotFrameWork\RobotFrameworkBasic\SuiteSiteTestePratico\AutomacaoDeTesteComRobotFramework_Basico\test\TestAPI.robot': Resource file 'ResourceAPI.robot' does not exist.</msg>
</errors>
</robot>
